/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.kisti.osp.spyglass.service.base;

import aQute.bnd.annotation.ProviderType;

import com.kisti.osp.spyglass.model.LogPorts;
import com.kisti.osp.spyglass.service.LogPortsLocalService;
import com.kisti.osp.spyglass.service.persistence.InputPortsPersistence;
import com.kisti.osp.spyglass.service.persistence.LayoutPersistence;
import com.kisti.osp.spyglass.service.persistence.LogPortsPersistence;
import com.kisti.osp.spyglass.service.persistence.OutputPortsPersistence;
import com.kisti.osp.spyglass.service.persistence.ScienceAppPersistence;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalServiceRegistry;
import com.liferay.portal.kernel.service.persistence.ClassNamePersistence;
import com.liferay.portal.kernel.service.persistence.UserPersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.spring.extender.service.ServiceReference;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the log ports local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.kisti.osp.spyglass.service.impl.LogPortsLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.kisti.osp.spyglass.service.impl.LogPortsLocalServiceImpl
 * @see com.kisti.osp.spyglass.service.LogPortsLocalServiceUtil
 * @generated
 */
@ProviderType
public abstract class LogPortsLocalServiceBaseImpl extends BaseLocalServiceImpl
	implements LogPortsLocalService, IdentifiableOSGiService {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link com.kisti.osp.spyglass.service.LogPortsLocalServiceUtil} to access the log ports local service.
	 */

	/**
	 * Adds the log ports to the database. Also notifies the appropriate model listeners.
	 *
	 * @param logPorts the log ports
	 * @return the log ports that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public LogPorts addLogPorts(LogPorts logPorts) {
		logPorts.setNew(true);

		return logPortsPersistence.update(logPorts);
	}

	/**
	 * Creates a new log ports with the primary key. Does not add the log ports to the database.
	 *
	 * @param scienceAppId the primary key for the new log ports
	 * @return the new log ports
	 */
	@Override
	@Transactional(enabled = false)
	public LogPorts createLogPorts(long scienceAppId) {
		return logPortsPersistence.create(scienceAppId);
	}

	/**
	 * Deletes the log ports with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param scienceAppId the primary key of the log ports
	 * @return the log ports that was removed
	 * @throws PortalException if a log ports with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public LogPorts deleteLogPorts(long scienceAppId) throws PortalException {
		return logPortsPersistence.remove(scienceAppId);
	}

	/**
	 * Deletes the log ports from the database. Also notifies the appropriate model listeners.
	 *
	 * @param logPorts the log ports
	 * @return the log ports that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public LogPorts deleteLogPorts(LogPorts logPorts) {
		return logPortsPersistence.remove(logPorts);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(LogPorts.class,
			clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return logPortsPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.kisti.osp.spyglass.model.impl.LogPortsModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery, int start,
		int end) {
		return logPortsPersistence.findWithDynamicQuery(dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.kisti.osp.spyglass.model.impl.LogPortsModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery, int start,
		int end, OrderByComparator<T> orderByComparator) {
		return logPortsPersistence.findWithDynamicQuery(dynamicQuery, start,
			end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return logPortsPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery,
		Projection projection) {
		return logPortsPersistence.countWithDynamicQuery(dynamicQuery,
			projection);
	}

	@Override
	public LogPorts fetchLogPorts(long scienceAppId) {
		return logPortsPersistence.fetchByPrimaryKey(scienceAppId);
	}

	/**
	 * Returns the log ports with the primary key.
	 *
	 * @param scienceAppId the primary key of the log ports
	 * @return the log ports
	 * @throws PortalException if a log ports with the primary key could not be found
	 */
	@Override
	public LogPorts getLogPorts(long scienceAppId) throws PortalException {
		return logPortsPersistence.findByPrimaryKey(scienceAppId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery = new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(logPortsLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(LogPorts.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("scienceAppId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery getIndexableActionableDynamicQuery() {
		IndexableActionableDynamicQuery indexableActionableDynamicQuery = new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(logPortsLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(LogPorts.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"scienceAppId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {
		actionableDynamicQuery.setBaseLocalService(logPortsLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(LogPorts.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("scienceAppId");
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {
		return logPortsLocalService.deleteLogPorts((LogPorts)persistedModel);
	}

	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {
		return logPortsPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the log portses.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.kisti.osp.spyglass.model.impl.LogPortsModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param start the lower bound of the range of log portses
	 * @param end the upper bound of the range of log portses (not inclusive)
	 * @return the range of log portses
	 */
	@Override
	public List<LogPorts> getLogPortses(int start, int end) {
		return logPortsPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of log portses.
	 *
	 * @return the number of log portses
	 */
	@Override
	public int getLogPortsesCount() {
		return logPortsPersistence.countAll();
	}

	/**
	 * Updates the log ports in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param logPorts the log ports
	 * @return the log ports that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public LogPorts updateLogPorts(LogPorts logPorts) {
		return logPortsPersistence.update(logPorts);
	}

	/**
	 * Returns the input ports local service.
	 *
	 * @return the input ports local service
	 */
	public com.kisti.osp.spyglass.service.InputPortsLocalService getInputPortsLocalService() {
		return inputPortsLocalService;
	}

	/**
	 * Sets the input ports local service.
	 *
	 * @param inputPortsLocalService the input ports local service
	 */
	public void setInputPortsLocalService(
		com.kisti.osp.spyglass.service.InputPortsLocalService inputPortsLocalService) {
		this.inputPortsLocalService = inputPortsLocalService;
	}

	/**
	 * Returns the input ports persistence.
	 *
	 * @return the input ports persistence
	 */
	public InputPortsPersistence getInputPortsPersistence() {
		return inputPortsPersistence;
	}

	/**
	 * Sets the input ports persistence.
	 *
	 * @param inputPortsPersistence the input ports persistence
	 */
	public void setInputPortsPersistence(
		InputPortsPersistence inputPortsPersistence) {
		this.inputPortsPersistence = inputPortsPersistence;
	}

	/**
	 * Returns the layout local service.
	 *
	 * @return the layout local service
	 */
	public com.kisti.osp.spyglass.service.LayoutLocalService getLayoutLocalService() {
		return layoutLocalService;
	}

	/**
	 * Sets the layout local service.
	 *
	 * @param layoutLocalService the layout local service
	 */
	public void setLayoutLocalService(
		com.kisti.osp.spyglass.service.LayoutLocalService layoutLocalService) {
		this.layoutLocalService = layoutLocalService;
	}

	/**
	 * Returns the layout persistence.
	 *
	 * @return the layout persistence
	 */
	public LayoutPersistence getLayoutPersistence() {
		return layoutPersistence;
	}

	/**
	 * Sets the layout persistence.
	 *
	 * @param layoutPersistence the layout persistence
	 */
	public void setLayoutPersistence(LayoutPersistence layoutPersistence) {
		this.layoutPersistence = layoutPersistence;
	}

	/**
	 * Returns the log ports local service.
	 *
	 * @return the log ports local service
	 */
	public LogPortsLocalService getLogPortsLocalService() {
		return logPortsLocalService;
	}

	/**
	 * Sets the log ports local service.
	 *
	 * @param logPortsLocalService the log ports local service
	 */
	public void setLogPortsLocalService(
		LogPortsLocalService logPortsLocalService) {
		this.logPortsLocalService = logPortsLocalService;
	}

	/**
	 * Returns the log ports persistence.
	 *
	 * @return the log ports persistence
	 */
	public LogPortsPersistence getLogPortsPersistence() {
		return logPortsPersistence;
	}

	/**
	 * Sets the log ports persistence.
	 *
	 * @param logPortsPersistence the log ports persistence
	 */
	public void setLogPortsPersistence(LogPortsPersistence logPortsPersistence) {
		this.logPortsPersistence = logPortsPersistence;
	}

	/**
	 * Returns the output ports local service.
	 *
	 * @return the output ports local service
	 */
	public com.kisti.osp.spyglass.service.OutputPortsLocalService getOutputPortsLocalService() {
		return outputPortsLocalService;
	}

	/**
	 * Sets the output ports local service.
	 *
	 * @param outputPortsLocalService the output ports local service
	 */
	public void setOutputPortsLocalService(
		com.kisti.osp.spyglass.service.OutputPortsLocalService outputPortsLocalService) {
		this.outputPortsLocalService = outputPortsLocalService;
	}

	/**
	 * Returns the output ports persistence.
	 *
	 * @return the output ports persistence
	 */
	public OutputPortsPersistence getOutputPortsPersistence() {
		return outputPortsPersistence;
	}

	/**
	 * Sets the output ports persistence.
	 *
	 * @param outputPortsPersistence the output ports persistence
	 */
	public void setOutputPortsPersistence(
		OutputPortsPersistence outputPortsPersistence) {
		this.outputPortsPersistence = outputPortsPersistence;
	}

	/**
	 * Returns the science app local service.
	 *
	 * @return the science app local service
	 */
	public com.kisti.osp.spyglass.service.ScienceAppLocalService getScienceAppLocalService() {
		return scienceAppLocalService;
	}

	/**
	 * Sets the science app local service.
	 *
	 * @param scienceAppLocalService the science app local service
	 */
	public void setScienceAppLocalService(
		com.kisti.osp.spyglass.service.ScienceAppLocalService scienceAppLocalService) {
		this.scienceAppLocalService = scienceAppLocalService;
	}

	/**
	 * Returns the science app persistence.
	 *
	 * @return the science app persistence
	 */
	public ScienceAppPersistence getScienceAppPersistence() {
		return scienceAppPersistence;
	}

	/**
	 * Sets the science app persistence.
	 *
	 * @param scienceAppPersistence the science app persistence
	 */
	public void setScienceAppPersistence(
		ScienceAppPersistence scienceAppPersistence) {
		this.scienceAppPersistence = scienceAppPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.kernel.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.kernel.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the class name local service.
	 *
	 * @return the class name local service
	 */
	public com.liferay.portal.kernel.service.ClassNameLocalService getClassNameLocalService() {
		return classNameLocalService;
	}

	/**
	 * Sets the class name local service.
	 *
	 * @param classNameLocalService the class name local service
	 */
	public void setClassNameLocalService(
		com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService) {
		this.classNameLocalService = classNameLocalService;
	}

	/**
	 * Returns the class name persistence.
	 *
	 * @return the class name persistence
	 */
	public ClassNamePersistence getClassNamePersistence() {
		return classNamePersistence;
	}

	/**
	 * Sets the class name persistence.
	 *
	 * @param classNamePersistence the class name persistence
	 */
	public void setClassNamePersistence(
		ClassNamePersistence classNamePersistence) {
		this.classNamePersistence = classNamePersistence;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.kernel.service.ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.kernel.service.UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.kernel.service.UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		persistedModelLocalServiceRegistry.register("com.kisti.osp.spyglass.model.LogPorts",
			logPortsLocalService);
	}

	public void destroy() {
		persistedModelLocalServiceRegistry.unregister(
			"com.kisti.osp.spyglass.model.LogPorts");
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return LogPortsLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return LogPorts.class;
	}

	protected String getModelClassName() {
		return LogPorts.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = logPortsPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = com.kisti.osp.spyglass.service.InputPortsLocalService.class)
	protected com.kisti.osp.spyglass.service.InputPortsLocalService inputPortsLocalService;
	@BeanReference(type = InputPortsPersistence.class)
	protected InputPortsPersistence inputPortsPersistence;
	@BeanReference(type = com.kisti.osp.spyglass.service.LayoutLocalService.class)
	protected com.kisti.osp.spyglass.service.LayoutLocalService layoutLocalService;
	@BeanReference(type = LayoutPersistence.class)
	protected LayoutPersistence layoutPersistence;
	@BeanReference(type = LogPortsLocalService.class)
	protected LogPortsLocalService logPortsLocalService;
	@BeanReference(type = LogPortsPersistence.class)
	protected LogPortsPersistence logPortsPersistence;
	@BeanReference(type = com.kisti.osp.spyglass.service.OutputPortsLocalService.class)
	protected com.kisti.osp.spyglass.service.OutputPortsLocalService outputPortsLocalService;
	@BeanReference(type = OutputPortsPersistence.class)
	protected OutputPortsPersistence outputPortsPersistence;
	@BeanReference(type = com.kisti.osp.spyglass.service.ScienceAppLocalService.class)
	protected com.kisti.osp.spyglass.service.ScienceAppLocalService scienceAppLocalService;
	@BeanReference(type = ScienceAppPersistence.class)
	protected ScienceAppPersistence scienceAppPersistence;
	@ServiceReference(type = com.liferay.counter.kernel.service.CounterLocalService.class)
	protected com.liferay.counter.kernel.service.CounterLocalService counterLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.ClassNameLocalService.class)
	protected com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService;
	@ServiceReference(type = ClassNamePersistence.class)
	protected ClassNamePersistence classNamePersistence;
	@ServiceReference(type = com.liferay.portal.kernel.service.ResourceLocalService.class)
	protected com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.UserLocalService.class)
	protected com.liferay.portal.kernel.service.UserLocalService userLocalService;
	@ServiceReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	@ServiceReference(type = PersistedModelLocalServiceRegistry.class)
	protected PersistedModelLocalServiceRegistry persistedModelLocalServiceRegistry;
}