/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.osp.spyglass.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;

import com.osp.spyglass.model.AssignedScheduler;
import com.osp.spyglass.model.AssignedSchedulerModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the AssignedScheduler service. Represents a row in the &quot;SPYGLASS_AssignedScheduler&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link AssignedSchedulerModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link AssignedSchedulerImpl}.
 * </p>
 *
 * @author Jerry H. Seo
 * @see AssignedSchedulerImpl
 * @see AssignedScheduler
 * @see AssignedSchedulerModel
 * @generated
 */
@ProviderType
public class AssignedSchedulerModelImpl extends BaseModelImpl<AssignedScheduler>
	implements AssignedSchedulerModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a assigned scheduler model instance should use the {@link AssignedScheduler} interface instead.
	 */
	public static final String TABLE_NAME = "SPYGLASS_AssignedScheduler";
	public static final Object[][] TABLE_COLUMNS = {
			{ "scienceAppId", Types.BIGINT },
			{ "assignedSchedulers", Types.VARCHAR }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("scienceAppId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("assignedSchedulers", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE = "create table SPYGLASS_AssignedScheduler (scienceAppId LONG not null primary key,assignedSchedulers VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table SPYGLASS_AssignedScheduler";
	public static final String ORDER_BY_JPQL = " ORDER BY assignedScheduler.scienceAppId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY SPYGLASS_AssignedScheduler.scienceAppId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.osp.spyglass.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.com.osp.spyglass.model.AssignedScheduler"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.osp.spyglass.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.com.osp.spyglass.model.AssignedScheduler"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.osp.spyglass.service.util.ServiceProps.get(
				"lock.expiration.time.com.osp.spyglass.model.AssignedScheduler"));

	public AssignedSchedulerModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _scienceAppId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setScienceAppId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _scienceAppId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return AssignedScheduler.class;
	}

	@Override
	public String getModelClassName() {
		return AssignedScheduler.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("scienceAppId", getScienceAppId());
		attributes.put("assignedSchedulers", getAssignedSchedulers());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long scienceAppId = (Long)attributes.get("scienceAppId");

		if (scienceAppId != null) {
			setScienceAppId(scienceAppId);
		}

		String assignedSchedulers = (String)attributes.get("assignedSchedulers");

		if (assignedSchedulers != null) {
			setAssignedSchedulers(assignedSchedulers);
		}
	}

	@Override
	public long getScienceAppId() {
		return _scienceAppId;
	}

	@Override
	public void setScienceAppId(long scienceAppId) {
		_scienceAppId = scienceAppId;
	}

	@Override
	public String getAssignedSchedulers() {
		if (_assignedSchedulers == null) {
			return "";
		}
		else {
			return _assignedSchedulers;
		}
	}

	@Override
	public void setAssignedSchedulers(String assignedSchedulers) {
		_assignedSchedulers = assignedSchedulers;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			AssignedScheduler.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public AssignedScheduler toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (AssignedScheduler)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		AssignedSchedulerImpl assignedSchedulerImpl = new AssignedSchedulerImpl();

		assignedSchedulerImpl.setScienceAppId(getScienceAppId());
		assignedSchedulerImpl.setAssignedSchedulers(getAssignedSchedulers());

		assignedSchedulerImpl.resetOriginalValues();

		return assignedSchedulerImpl;
	}

	@Override
	public int compareTo(AssignedScheduler assignedScheduler) {
		long primaryKey = assignedScheduler.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof AssignedScheduler)) {
			return false;
		}

		AssignedScheduler assignedScheduler = (AssignedScheduler)obj;

		long primaryKey = assignedScheduler.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<AssignedScheduler> toCacheModel() {
		AssignedSchedulerCacheModel assignedSchedulerCacheModel = new AssignedSchedulerCacheModel();

		assignedSchedulerCacheModel.scienceAppId = getScienceAppId();

		assignedSchedulerCacheModel.assignedSchedulers = getAssignedSchedulers();

		String assignedSchedulers = assignedSchedulerCacheModel.assignedSchedulers;

		if ((assignedSchedulers != null) && (assignedSchedulers.length() == 0)) {
			assignedSchedulerCacheModel.assignedSchedulers = null;
		}

		return assignedSchedulerCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(5);

		sb.append("{scienceAppId=");
		sb.append(getScienceAppId());
		sb.append(", assignedSchedulers=");
		sb.append(getAssignedSchedulers());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(10);

		sb.append("<model><model-name>");
		sb.append("com.osp.spyglass.model.AssignedScheduler");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>scienceAppId</column-name><column-value><![CDATA[");
		sb.append(getScienceAppId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>assignedSchedulers</column-name><column-value><![CDATA[");
		sb.append(getAssignedSchedulers());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = AssignedScheduler.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			AssignedScheduler.class, ModelWrapper.class
		};
	private long _scienceAppId;
	private String _assignedSchedulers;
	private AssignedScheduler _escapedModel;
}