/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.osp.spyglass.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;

import com.osp.spyglass.model.InputPorts;
import com.osp.spyglass.model.InputPortsModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the InputPorts service. Represents a row in the &quot;SPYGLASS_InputPorts&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link InputPortsModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link InputPortsImpl}.
 * </p>
 *
 * @author Jerry H. Seo
 * @see InputPortsImpl
 * @see InputPorts
 * @see InputPortsModel
 * @generated
 */
@ProviderType
public class InputPortsModelImpl extends BaseModelImpl<InputPorts>
	implements InputPortsModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a input ports model instance should use the {@link InputPorts} interface instead.
	 */
	public static final String TABLE_NAME = "SPYGLASS_InputPorts";
	public static final Object[][] TABLE_COLUMNS = {
			{ "scienceAppId", Types.BIGINT },
			{ "inputPorts", Types.VARCHAR }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("scienceAppId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("inputPorts", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE = "create table SPYGLASS_InputPorts (scienceAppId LONG not null primary key,inputPorts VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table SPYGLASS_InputPorts";
	public static final String ORDER_BY_JPQL = " ORDER BY inputPorts.scienceAppId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY SPYGLASS_InputPorts.scienceAppId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.osp.spyglass.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.com.osp.spyglass.model.InputPorts"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.osp.spyglass.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.com.osp.spyglass.model.InputPorts"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.osp.spyglass.service.util.ServiceProps.get(
				"lock.expiration.time.com.osp.spyglass.model.InputPorts"));

	public InputPortsModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _scienceAppId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setScienceAppId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _scienceAppId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return InputPorts.class;
	}

	@Override
	public String getModelClassName() {
		return InputPorts.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("scienceAppId", getScienceAppId());
		attributes.put("inputPorts", getInputPorts());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long scienceAppId = (Long)attributes.get("scienceAppId");

		if (scienceAppId != null) {
			setScienceAppId(scienceAppId);
		}

		String inputPorts = (String)attributes.get("inputPorts");

		if (inputPorts != null) {
			setInputPorts(inputPorts);
		}
	}

	@Override
	public long getScienceAppId() {
		return _scienceAppId;
	}

	@Override
	public void setScienceAppId(long scienceAppId) {
		_scienceAppId = scienceAppId;
	}

	@Override
	public String getInputPorts() {
		if (_inputPorts == null) {
			return "";
		}
		else {
			return _inputPorts;
		}
	}

	@Override
	public void setInputPorts(String inputPorts) {
		_inputPorts = inputPorts;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			InputPorts.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public InputPorts toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (InputPorts)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		InputPortsImpl inputPortsImpl = new InputPortsImpl();

		inputPortsImpl.setScienceAppId(getScienceAppId());
		inputPortsImpl.setInputPorts(getInputPorts());

		inputPortsImpl.resetOriginalValues();

		return inputPortsImpl;
	}

	@Override
	public int compareTo(InputPorts inputPorts) {
		long primaryKey = inputPorts.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof InputPorts)) {
			return false;
		}

		InputPorts inputPorts = (InputPorts)obj;

		long primaryKey = inputPorts.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<InputPorts> toCacheModel() {
		InputPortsCacheModel inputPortsCacheModel = new InputPortsCacheModel();

		inputPortsCacheModel.scienceAppId = getScienceAppId();

		inputPortsCacheModel.inputPorts = getInputPorts();

		String inputPorts = inputPortsCacheModel.inputPorts;

		if ((inputPorts != null) && (inputPorts.length() == 0)) {
			inputPortsCacheModel.inputPorts = null;
		}

		return inputPortsCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(5);

		sb.append("{scienceAppId=");
		sb.append(getScienceAppId());
		sb.append(", inputPorts=");
		sb.append(getInputPorts());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(10);

		sb.append("<model><model-name>");
		sb.append("com.osp.spyglass.model.InputPorts");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>scienceAppId</column-name><column-value><![CDATA[");
		sb.append(getScienceAppId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>inputPorts</column-name><column-value><![CDATA[");
		sb.append(getInputPorts());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = InputPorts.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			InputPorts.class, ModelWrapper.class
		};
	private long _scienceAppId;
	private String _inputPorts;
	private InputPorts _escapedModel;
}