/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.kisti.osp.util.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the Util service. Represents a row in the &quot;OSPUTIL_Util&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.kisti.osp.util.model.impl.UtilModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.kisti.osp.util.model.impl.UtilImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Util
 * @see com.kisti.osp.util.model.impl.UtilImpl
 * @see com.kisti.osp.util.model.impl.UtilModelImpl
 * @generated
 */
@ProviderType
public interface UtilModel extends BaseModel<Util>, ShardedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a util model instance should use the {@link Util} interface instead.
	 */

	/**
	 * Returns the primary key of this util.
	 *
	 * @return the primary key of this util
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this util.
	 *
	 * @param primaryKey the primary key of this util
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this util.
	 *
	 * @return the uuid of this util
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this util.
	 *
	 * @param uuid the uuid of this util
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the util ID of this util.
	 *
	 * @return the util ID of this util
	 */
	public long getUtilId();

	/**
	 * Sets the util ID of this util.
	 *
	 * @param utilId the util ID of this util
	 */
	public void setUtilId(long utilId);

	/**
	 * Returns the group ID of this util.
	 *
	 * @return the group ID of this util
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this util.
	 *
	 * @param groupId the group ID of this util
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this util.
	 *
	 * @return the company ID of this util
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this util.
	 *
	 * @param companyId the company ID of this util
	 */
	@Override
	public void setCompanyId(long companyId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Util util);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Util> toCacheModel();

	@Override
	public Util toEscapedModel();

	@Override
	public Util toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}