package com.osp.spyglass.constants;

public enum RunTypes {
	SEQUENTIAL,
	GAMESS_PARALLEL,
	GNU_OPENMP_MPI,
	GNU_MPICH_1,
	GNU_MPICH_2,
	GNU_OPENMPI_1_4,
	GNU_OPENMP,
	INTEL_OPENMP_MPI,
	INTEL_MPICH_1,
	INTEL_MPICH_2,
	INTEL_OPENMPI_1_4,
	INTEL_OPENMP
}
